#!/bin/bash
function bake {
  get_recipe_description=`wget -qO- https://raw.githubusercontent.com/uni-linux/recipes/master/src/$recipe/README.md | grep -P '^[^\|;|]*$' | grep -v '\#\sUsage'`
  is_available_recipe=`wget -qO- https://raw.githubusercontent.com/uni-linux/recipes/master/src/$recipe/$operating_system/recipe.sh`
  cols=`tput cols`

  if [[ ! -z $is_available_recipe ]]; then

      while (( i <= $cols-1 )); do
            lines+='-'
      (( i = i + 1 ))
      done

      printf "\n$lines\n# IT'S TIME TO COOK $recipe!\n$lines\n\n$get_recipe_description\n\n$lines\n\nCooking...\n"
      wget -O uni-recipe.sh https://raw.githubusercontent.com/uni-linux/recipes/master/src/$recipe/$operating_system/recipe.sh -q
      printf "Eating...\n"
      chmod +x uni-recipe.sh
      printf "\n$lines\n\n"
      . uni-recipe.sh
      rm -f uni-recipe.sh
      printf "\n$lines\n\nDone. It was delicious!\n\n"
  else
      printf "\nThis recipe doesn't seems to exist.\nPlease, check if you have typed correctly or if it's available for your distribution!\n\n"
  fi
}
