#!/bin/bash
function upgradeUni {
  version_from_github=`wget -qO- https://git.io/v1JFY`
  declare -i  version_without_dots_from_github="${get_version_from_github//'.'}"

  printf "Looking for a newest version...\n"

  if [ "$version_without_dots" -lt "$version_without_dots_from_github" ]; then

      printf "Yes, there's a new version. \nInstalling v$version_from_github...\n"

      wget -O uni-new https://git.io/v1Jbs -q
      unzip -q uni-new
      rm -f uni-new
      sudo rm -rf /usr/share/uni/
      mv uni-master uni
      sudo mv -fu uni /usr/share/

      printf "Done. UNI was upgraded with successfully!\n"
  else
      printf 'UNI is up-to-date!\n'
  fi
  exit 0
}
